name: AUR CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      GIT_SSH_COMMAND: "ssh -i key -o StrictHostKeyChecking=no"
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        echo "${DEPLOY_KEY}" > key
        git remote add aur ssh://aur.archlinux.org/st-highdpi-git.git
        makepkg --printsrcinfo > .SRCINFO
        git add .SRCINFO
        git commit -m 'update SRCINFO'
        git push -f aur master
